# Default initial positions for adam_u's ros2_control fake system

initial_positions:
  L_index_DIP_joint: 0
  L_index_MCP_joint: 0
  L_middle_DIP_joint: 0
  L_middle_MCP_joint: 0
  L_pinky_DIP_joint: 0
  L_pinky_MCP_joint: 0
  L_ring_DIP_joint: 0
  L_ring_MCP_joint: 0
  L_thumb_DIP_joint: 0
  L_thumb_MCP_joint1: 0
  L_thumb_MCP_joint2: 0
  L_thumb_PIP_joint: 0
  R_index_DIP_joint: 0
  R_index_MCP_joint: 0
  R_middle_DIP_joint: 0
  R_middle_MCP_joint: 0
  R_pinky_DIP_joint: 0
  R_pinky_MCP_joint: 0
  R_ring_DIP_joint: 0
  R_ring_MCP_joint: 0
  R_thumb_DIP_joint: 0
  R_thumb_MCP_joint1: 0
  R_thumb_MCP_joint2: 0
  R_thumb_PIP_joint: 0
  elbow_Left: 0
  elbow_Right: -1.5
  neckPitch: 0
  neckYaw: 0
  shoulderPitch_Left: 0
  shoulderPitch_Right: -0.5
  shoulderRoll_Left: 0
  shoulderRoll_Right: -0.2
  shoulderYaw_Left: 0
  shoulderYaw_Right: 0.0
  waistPitch: 0
  waistRoll: -0.0
  waistYaw: 0
  wristPitch_Left: 0
  wristPitch_Right: 0
  wristRoll_Left: 0
  wristRoll_Right: -0.3
  wristYaw_Left: 0
  wristYaw_Right: 0


